# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          github_token: ${{ secrets.TOKEN_GITHUB }}
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Set git config username
        run: git config --global user.name "$GIT_USERNAME"
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - name: Set git config email
        run: git config --global user.email "$GIT_EMAIL"
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      - name: Commit change after build
        run: git add . && git commit -am "after build from workflow"
      - name: Patch npm version
        run:  npm version patch
      - name: git fetch
        run: git fetch
      - name: checkout master
        run: git checkout master
      - name: push change after upgrade version
        run: git push origin master
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
